@43622 	A vastly more informative error message.
	Prior to this edit, you would get something like this:
	
	  java.lang.IllegalArgumentException: All column constraints must be
	  from the same table.
	      at com.redhat.persistence.metadata.Constraint.<init>(Constraint.java:65)
	      at com.redhat.persistence.metadata.UniqueKey.<init>(UniqueKey.java:34)
	      at com.redhat.persistence.pdl.PDL.unique(PDL.java:459)
	      at com.redhat.persistence.pdl.PDL.unique(PDL.java:533)
	      at com.redhat.persistence.pdl.PDL.access$800(PDL.java:34)
	      at com.redhat.persistence.pdl.PDL$12.onObjectKey(PDL.java:579)
	      at com.redhat.persistence.pdl.nodes.ObjectKeyNd.dispatch(ObjectKeyNd.java:35)
	      at com.redhat.persistence.pdl.nodes.Node.traverse(Node.java:226)
	      at com.redhat.persistence.pdl.nodes.Node.traverse(Node.java:230)
	      at com.redhat.persistence.pdl.nodes.Node.traverse(Node.java:230)
	      at com.redhat.persistence.pdl.nodes.Node.traverse(Node.java:230)
	      at com.redhat.persistence.pdl.PDL.emitDDL(PDL.java:577)
	      at com.redhat.persistence.pdl.PDL.emit(PDL.java:349)
	
	
	After this edit, you get:
	
	  java.lang.IllegalArgumentException: All column constraints must be
	  from the same table. table=mag_index;
	  columns=[mag_index.magazine_id, mag_index_emails.index]; offending
	  column=mag_index_emails.index
	      at com.redhat.persistence.metadata.Constraint.<init>(Constraint.java:65)
	      at com.redhat.persistence.metadata.UniqueKey.<init>(UniqueKey.java:34)
	      at com.redhat.persistence.pdl.PDL.unique(PDL.java:459)
	
	which makes it obvious that the root cause of the exception is the
	misspelled table name ("mag_index_email" instead of the correct
	"mag_index").