@44501 	Fixed enhancement errors.  Classes are now enhanced correctly.  Where 	we used to get a bunch of failures due to the failure to enhance, we 	now get exceptions similar to this:
	java.lang.IllegalStateException: no type for com.sun.jdotck.models.mylib.PCPoint
	    at com.redhat.persistence.jdo.PersistenceManagerImpl.makePersistent(PersistenceManagerImpl.java:365)
	
	This puts the ball squarely in Rafi's court.
	
	Here's how we worked around the enhancer's previous failure to enhance.
	
	Prior to this change, we were trying to rename
	datastore/tests/com/*.jdo.d files to build/datastore/classes/com/*.jdo.
	We also used to performe the following additional renamings.  These
	three files:
	
	  datastore/tests/com/sun/jdotck/models/company.jdo.d
	  datastore/tests/com/sun/jdotck/models/inheritance.jdo.d
	  datastore/tests/com/sun/jdotck/models/mylib.jdo.d
	
	do not conform to naming convention described by the spec.  This causes
	these three files to be ignored by the enhancer.  So, we renamed these
	to
	
	  build/datastore/classes/com/sun/jdotck/models/company/package.jdo
	  build/datastore/classes/com/sun/jdotck/models/inheritance/package.jdo
	  build/datastore/classes/com/sun/jdotck/models/mylib/package.jdo
	
	The remaining unresolved problem was that all of the *.jdo.d files
	specify a relative path to the JDO DTD.  Crimson (the validating parser
	shipped with JDK 1.4) was failing to find said DTD.
	
	All of these problems are solved by noting that the directory
	datastore/jdo_files/ contains properly renamed and edited *.jdo files.
	(I suspect this was added by the JPOX guys when they ran into the same
	problems.)