@43380 	Minor changes: added a couple of new constructors in AbstractCase and 	PandoraTest to make it possible to run a single test by explicitly 	naming it in JDOSuite.  Added some log4j debugging code.
	Major changes: In PandoraTest#testMain, Order instances used to be
	constructed via Main#create, which works cglib magic.  In this change,
	we switched to using plaing old "new Order()" instead.  Also added
	calls to pm.makePersistent(order) on the newly constructed orders.
	Currently getting the following exception,
	
	com.redhat.persistence.FlushException: Unable to send all events to
	database because these required properties are null:
	 <item #38>.order
	 <item #17>.order
	...
	 <item #42>.order
	        at com.redhat.persistence.Session.flushAll(Session.java:660)
	        at com.redhat.persistence.jdotest.PandoraTest.testMain(PandoraTest.java:338)
	
	where the required property "order" is missing from items #10 through
	#99.  The first ten items (corresponding to order #0) are getting their
	"order" property set correctly.
	
	For the very first order (order #0), the call to Order#getItems()
	correctly returns an instance of CRPSet.  For subsequent calls (for
	orders #1 through #9), it returns a LinkedList.
	
	Rafi figured out what the problem is.  I am going to submit a fix with
	the next change.  (Splitting it out into a separate change strictly for
	educational purposes.)